import type { Metadata } from "next";
import "./globals.css";

import { Nav } from "./components/Nav";
import { Spartan } from "./fonts";
import Footer from "./components/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html lang="ar" dir="ltr" className={` h-full antialiased`}>
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.3.1/css/all.min.css"
        />
      </head>
      <body className={`min-h-full flex flex-col   ${Spartan.className}`}>
        <Nav />
        <div className="mt-18">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
